server:
  port: 8080
spring:
  application:
    name: "RollTheBlock"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  restconsumer:
    url: "C:/Program Files/Git/v1/mine"
